### ISSUE TITLE
Failure to Forward Request

### ISSUE THREAD

**Issue by gzye** [cisco-ie/webex-api-client#1]
Hello there, 

I am having issues with the code, not sure if there is something I am omitting or whether the XML version has been updated and no longer compatible with this module.

When copying the example, adding my credentials, I appear to get the following response:

`<?xml version="1.0" encoding="UTF-8" ?>
<serv:message xmlns:serv="http://www.webex.com/schemas/2002/06/service" xmlns:com="http://www.webex.com/schemas/2002/06/common">
<serv:header>
<serv:response>
<serv:result>FAILURE</serv:result>
<serv:reason>Fail to forward request:null</serv:reason>
<serv:gsbStatus>PRIMARY</serv:gsbStatus>
<serv:exceptionID>000000</serv:exceptionID></serv:response>
</serv:header>
<serv:body>
</serv:body>
</serv:message>`

Which after looking through the Cisco Dev forums, I have found the same issue with the solution of removing the newlines and spaces from the XML request, however I am not sure how that would be achieved using the builder function.

[CiscoDev Article Link](https://communities.cisco.com/message/231522#231522)

**Comment by brh55** [comment]
@gzye It would appear to be related to spacing / new lines, however the module itself doesn't generate any whitespace or newlines. I did a little bit of digging and realize I needed to add an attribute to the `<serv:message>`.

**Comment by gzye** [comment]
Awesome, thanks :)

**Comment by brh55** [comment]
@gzye 

Please update to v0.2.1, this should fix most issues I was confronted with. Let me know if you run into further issues.

**Comment by gzye** [comment]
Perfect, thank you.
