### ISSUE TITLE
updateMeeting has slow response times

### ISSUE THREAD

**Issue by gk159yo** [cisco-ie/webex-api-client#11]
I know this has nothing to do with the webex-api-client, so please close this issue once you have looked at it, but the `updateMeeting` service is takes really long to respond.
Is this a known issue?

**Comment by brh55** [comment]
@gk159yo I don't believe this is a known issue currently. Have you tried reaching through DevNet support?

**Comment by gk159yo** [comment]
No, I haven't. I'm banking on this being an issue in the dev sandbox only.
I will contact DevNet if this issue persists on prod.
