### ISSUE TITLE
Syntax error with the xml-builder

### ISSUE THREAD

**Issue by CGrijalva90** [cisco-ie/webex-api-client#6]
I installed the package and tried running it, but I'm getting the following error from the node_modules:

`webex/node_modules/webex-api-client/src/xml-builder.js:24
                                                ...root[rootName],
                                                ^^^`
`SyntaxError: Unexpected token ...`

Problem is specifically in the use of the spread operator it seems:

```
const newObject = {
    [rootName]: {
        ...root[rootName],
        ...jsObject
    }
};
```

Due to this, the server is unable to run.

**Comment by brh55** [comment]
Hey @CGrijalva90 , hopefully you have this resolved, but this can be solved with updating your node version.

**Comment by CGrijalva90** [comment]
Hey @brh55 Thanks for the prompt reply. I'm using `v8.2.1`, figure it should work on this version no?
