### ISSUE TITLE
Multiple attendees can't be added to a `CreateMeeting` request

### ISSUE THREAD

**Issue by gk159yo** [cisco-ie/webex-api-client#7]
Try making a meeting with multiple participants.
Server will reject your request b/c the generated xml will look like this:

`
<attendees>
   <ATTENDEE 1>
</attendees>
<attendees>
   <ATTENDEE 2>
</attendees>
`
instead of like this:
`
<attendees>
   <ATTENDEE 1>
   <ATTENDEE 2>
</attendees>
`

The former is rejected by the server, which expects only one `<attendees>` in the xml payload.

Its b/c of how xml2js works:
https://github.com/Leonidas-from-XIV/node-xml2js/issues/428

I can make a quick PR to fix this if this library still has a maintainer.

**Comment by brh55** [comment]
@gk159yo Feel free to submit a PR, we aren't currently using the library in our current projects, but we do use it for any webex related projects.

**Comment by gk159yo** [comment]
@brh55 here's a PR:
https://github.com/cisco-ie/webex-api-client/pull/8

I pasted the file I had on local. Please let me know if it doesn't work.

**Comment by gk159yo** [comment]
PR: #10
